In [24]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
from math import sqrt

In [2]:
DATA_PATH = "data"

In [3]:
os.listdir(DATA_PATH)

['Team.csv',
 'Player.csv',
 'League.csv',
 'Team_Attributes.csv',
 'Country.csv',
 'Player_Attributes.csv',
 'Match.csv']

In [4]:
player_attr_raw = pd.read_csv(os.path.join(DATA_PATH, 'Player_Attributes.csv'))
player_attr_raw.head()

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [5]:
player_attr_raw.shape

(183978, 42)

In [6]:
player_attr = player_attr_raw.dropna()
player_attr.shape

(180354, 42)

In [7]:
player_attr['preferred_foot'].unique()

array(['right', 'left'], dtype=object)

In [8]:
player_attr['attacking_work_rate'].unique()

array(['medium', 'high', 'low', 'None', 'le', 'norm', 'stoc', 'y'],
      dtype=object)

In [9]:
player_attr['defensive_work_rate'].unique()

array(['medium', 'high', 'low', '5', 'ean', 'o', '1', 'ormal', '7', '2',
       '8', '4', 'tocky', '0', '3', '6', '9', 'es'], dtype=object)

In [10]:
player_attr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180354 entries, 0 to 183977
Data columns (total 42 columns):
id                     180354 non-null int64
player_fifa_api_id     180354 non-null int64
player_api_id          180354 non-null int64
date                   180354 non-null object
overall_rating         180354 non-null float64
potential              180354 non-null float64
preferred_foot         180354 non-null object
attacking_work_rate    180354 non-null object
defensive_work_rate    180354 non-null object
crossing               180354 non-null float64
finishing              180354 non-null float64
heading_accuracy       180354 non-null float64
short_passing          180354 non-null float64
volleys                180354 non-null float64
dribbling              180354 non-null float64
curve                  180354 non-null float64
free_kick_accuracy     180354 non-null float64
long_passing           180354 non-null float64
ball_control           180354 non-null float64
acceleration           180354 non-null float64
sprint_speed           180354 non-null float64
agility                180354 non-null float64
reactions              180354 non-null float64
balance                180354 non-null float64
shot_power             180354 non-null float64
jumping                180354 non-null float64
stamina                180354 non-null float64
strength               180354 non-null float64
long_shots             180354 non-null float64
aggression             180354 non-null float64
interceptions          180354 non-null float64
positioning            180354 non-null float64
vision                 180354 non-null float64
penalties              180354 non-null float64
marking                180354 non-null float64
standing_tackle        180354 non-null float64
sliding_tackle         180354 non-null float64
gk_diving              180354 non-null float64
gk_handling            180354 non-null float64
gk_kicking             180354 non-null float64
gk_positioning         180354 non-null float64
gk_reflexes            180354 non-null float64
dtypes: float64(35), int64(3), object(4)
memory usage: 59.2+ MB

In [16]:
vectorized_players_df = player_attr.drop(columns=['id','player_fifa_api_id',
                                               'player_api_id', 'date', 
                                               'preferred_foot', 'attacking_work_rate',
                                               'defensive_work_rate', 'overall_rating',
                                            'potential'])
vectorized_players_df.head()

,overall_rating,potential,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,67.0,71.0,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,67.0,71.0,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,62.0,66.0,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,61.0,65.0,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,61.0,65.0,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [17]:
vectorized_players_df.shape

(180354, 35)

In [33]:
vectorized_players_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180354 entries, 0 to 183977
Data columns (total 35 columns):
overall_rating        180354 non-null float64
potential             180354 non-null float64
crossing              180354 non-null float64
finishing             180354 non-null float64
heading_accuracy      180354 non-null float64
short_passing         180354 non-null float64
volleys               180354 non-null float64
dribbling             180354 non-null float64
curve                 180354 non-null float64
free_kick_accuracy    180354 non-null float64
long_passing          180354 non-null float64
ball_control          180354 non-null float64
acceleration          180354 non-null float64
sprint_speed          180354 non-null float64
agility               180354 non-null float64
reactions             180354 non-null float64
balance               180354 non-null float64
shot_power            180354 non-null float64
jumping               180354 non-null float64
stamina               180354 non-null float64
strength              180354 non-null float64
long_shots            180354 non-null float64
aggression            180354 non-null float64
interceptions         180354 non-null float64
positioning           180354 non-null float64
vision                180354 non-null float64
penalties             180354 non-null float64
marking               180354 non-null float64
standing_tackle       180354 non-null float64
sliding_tackle        180354 non-null float64
gk_diving             180354 non-null float64
gk_handling           180354 non-null float64
gk_kicking            180354 non-null float64
gk_positioning        180354 non-null float64
gk_reflexes           180354 non-null float64
dtypes: float64(35)
memory usage: 49.5 MB

In [18]:
vectorized_players_df.describe()

,overall_rating,potential,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
count,180354.000000,180354.000000,180354.000000,180354.000000,180354.000000,180354.000000,180354.000000,180354.000000,180354.000000,180354.000000,...,180354.000000,180354.000000,180354.000000,180354.000000,180354.000000,180354.000000,180354.000000,180354.000000,180354.000000,180354.00000
mean,68.635317,73.479457,55.142071,49.962136,57.263476,62.486726,49.488927,59.265755,53.001408,49.392783,...,57.868176,54.933448,46.757433,50.354065,48.029342,14.696685,15.947786,20.526304,16.015043,16.32531
std,7.027950,6.581963,17.247231,19.041760,16.478716,14.172493,18.252319,17.741351,18.245476,17.820262,...,15.152408,15.556645,21.226730,21.496289,21.592830,16.841454,15.841297,21.143898,16.070772,17.18545
min,33.000000,39.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,2.000000,1.000000,...,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.00000
25%,64.000000,69.000000,45.000000,34.000000,49.000000,57.000000,35.000000,52.000000,41.000000,36.000000,...,49.000000,45.000000,25.000000,29.000000,25.000000,7.000000,8.000000,8.000000,8.000000,8.00000
50%,69.000000,74.000000,59.000000,53.000000,60.000000,65.000000,52.000000,64.000000,56.000000,50.000000,...,60.000000,57.000000,50.000000,56.000000,53.000000,10.000000,11.000000,12.000000,11.000000,11.00000
75%,73.000000,78.000000,68.000000,65.000000,68.000000,72.000000,64.000000,72.000000,67.000000,63.000000,...,69.000000,67.000000,66.000000,69.000000,67.000000,13.000000,15.000000,15.000000,15.000000,15.00000
max,94.000000,97.000000,95.000000,97.000000,98.000000,97.000000,93.000000,97.000000,94.000000,97.000000,...,97.000000,96.000000,94.000000,95.000000,95.000000,94.000000,93.000000,97.000000,96.000000,96.00000

In [19]:
vectorized_players = vectorized_players_df.values

In [25]:
def dist(a,b):
    return np.linalg.norm(a-b)

def Gonzales(data, c1, k=3):
    n = len(data)
    assignments = dict([(_, 0) for _ in range(n)])
    clusters = np.empty((k, len(c1)))
    clusters[0,:] = c1
    for i in range(1,k):
        m = 0
        clusters[i,:] = data[0]
        for j in range(n):
            if dist(data[j,:], clusters[assignments[j], :]) > m:
                m = dist(data[j,:], clusters[assignments[j], :])
                clusters[i,:] = data[j,:]
                
        for j in range(n):
            if dist(data[j,:], clusters[assignments[j], :]) > dist(data[j,:], clusters[i,:]):
                assignments[j] = i
    arr = [dist(d, clusters[assignments[idx],:]) for idx,d in enumerate(data)]
    max3cenCost = max(arr)
    mean3Cost = sqrt(sum([x**2 for x in arr])/len(arr))
    print(max3cenCost, mean3Cost)
    print(clusters)
    data = np.append(data, np.array([[i] for i in list(assignments.values())]), axis=1)
    return data, max3cenCost, mean3Cost, clusters

In [35]:
clusters, three_cen_cost, three_mean_cost, centers = Gonzales(vectorized_players, vectorized_players[0,:], k=2)

239.46607275353225 108.59209976322788
[[67. 71. 49. 44. 71. 61. 44. 51. 45. 39. 64. 49. 60. 64. 59. 47. 65. 55.
  58. 54. 76. 35. 71. 70. 45. 54. 48. 65. 69. 69.  6. 11. 10.  8.  8.]
 [93. 93.  9. 10.  8. 23.  7.  9.  8. 88. 76. 22. 62. 44. 65. 89. 67. 24.
  75. 56. 83.  9. 81. 90. 14. 70. 88.  8.  8.  9. 91. 93. 76. 96. 93.]]

In [36]:
clusters.shape

(180354, 36)

In [37]:
centers

array([[67., 71., 49., 44., 71., 61., 44., 51., 45., 39., 64., 49., 60.,
        64., 59., 47., 65., 55., 58., 54., 76., 35., 71., 70., 45., 54.,
        48., 65., 69., 69.,  6., 11., 10.,  8.,  8.],
       [93., 93.,  9., 10.,  8., 23.,  7.,  9.,  8., 88., 76., 22., 62.,
        44., 65., 89., 67., 24., 75., 56., 83.,  9., 81., 90., 14., 70.,
        88.,  8.,  8.,  9., 91., 93., 76., 96., 93.]])